"""
config.py — Central configuration for the patch-seq data preparation pipeline.

All file paths, analysis parameters, and constants are defined here.
Modules import from this file rather than hardcoding values.

Path resolution:
  PROJECT_ROOT is auto-detected from this file's location (patchseq_builder/ is
  a direct child of the project root). All other paths are relative to it.
"""
from pathlib import Path

# ============================================================================
# Project root (auto-detected, no hardcoded absolute paths)
# ============================================================================

PROJECT_ROOT = Path(__file__).parent.parent

# ============================================================================
# Raw input data (not generated by this pipeline)
# ============================================================================

DATA_DIR = PROJECT_ROOT / "data" / "patchseq"

# LeeDalley dataset (779 cells, MTG patch-seq, multiple layers)
# Source: github.com/AllenInstitute/human_patchseq_gaba (Lee & Dalley et al. Science 2023)
LD_DATA_DIR = PROJECT_ROOT / "human_patchseq_gaba" / "data"
LD_METADATA_CSV = LD_DATA_DIR / "LeeDalley_manuscript_metadata_v2.csv"
LD_EPHYS_CSV = LD_DATA_DIR / "LeeDalley_ephys_fx.csv"
LD_MORPHO_FEATURES_CSV = LD_DATA_DIR / "LeeDalley_morpho_features.csv"
LD_DONOR_TABLE_CSV = LD_DATA_DIR / "DataS1_Donor_table.csv"
LD_RDATA = PROJECT_ROOT / "complete_patchseq_data_sets.RData"

# L1 dataset (419 cells, human L1 interneurons, Chartrand et al. Science 2023)
# Source: github.com/AllenInstitute/patchseq_human_L1
L1_DATA_DIR = PROJECT_ROOT / "patchseq_human_L1" / "data"
L1_METADATA_CSV = L1_DATA_DIR / "human_l1_dataset_2023_02_06.csv"
L1_EPHYS_CSV = L1_DATA_DIR / "aibs_features_E.csv"
L1_LAYER_DEPTHS_CSV = L1_DATA_DIR / "human_layer_depths_2023_02_06.csv"
L1_RDATA = L1_DATA_DIR / "ps_human.RData"
L1_DONOR_TABLE_XLSX = DATA_DIR / "science.adf0805_data_s1.xlsx"  # Chartrand et al. Data S1

# scANVI label transfer results (4,549 cells → SEA-AD supertypes)
SCANVI_RESULTS_CSV = DATA_DIR / "iterative_scANVI_results_patchseq_only.2022-11-22.csv"

# SEA-AD snRNA-seq reference (for integration, symlink to ~/Github/shared_data/)
SEAAD_H5AD = PROJECT_ROOT / "data" / "seaad_reference.h5ad"

# Allen Institute color scheme (optional external repo)
ALLEN_COLORS_JSON = (
    PROJECT_ROOT.parent / "SCZ_Xenium" / "output" / "deploy" / "index.json"
)

# ============================================================================
# External data repositories
# ============================================================================

# Sam Mestern's intraDANDI explorer (pre-generated trace SVGs)
INTRADANDI_DIR = PROJECT_ROOT / "intraDANDI_explorer-master"
INTRADANDI_TRACES_DIR = INTRADANDI_DIR / "data" / "traces"

# DANDI dandisets containing our patch-seq recordings
DANDI_DANDISETS = {
    "000636": {"lab": "LeeDalley/AIBS", "n_nwbs": 691},
    "000630": {"lab": "L1/AIBS", "n_nwbs": 210},
    "000228": {"lab": "lab-28/Lee-Bhatt", "n_nwbs": 91},
    "000337": {"lab": "lab-29", "n_nwbs": 21},
}

# BIL (Brain Image Library) SWC download URL templates
BIL_DIRECT_URLS = [
    ("group_20230426", "https://download.brainimagelibrary.org/group/20230426/swc/{sid}/{sid}_upright.swc"),
    ("d833_upright", "https://download.brainimagelibrary.org/d8/33/d833ba8bd931f23f/{sid}/{sid}_upright.swc"),
    ("efb9_upright", "https://download.brainimagelibrary.org/ef/b9/efb9b12ba2fab63d/{sid}/{sid}_upright.swc"),
    ("49e6_upright", "https://download.brainimagelibrary.org/49/e6/49e6114ba67eda01/{sid}/{sid}_upright.swc"),
    ("85f4_upright", "https://download.brainimagelibrary.org/85/f4/85f4b93699151f1c/{sid}/{sid}_upright.swc"),
    ("241a_transformed", "https://download.brainimagelibrary.org/24/1a/241a10cde842c99b/{sid}/{sid}_transformed.swc"),
]
BIL_69FE_DIR = "https://download.brainimagelibrary.org/69/fe/69fe931fee2b2215/{sid}/"

# ============================================================================
# Generated output paths
# ============================================================================

RESULTS_DIR = PROJECT_ROOT / "results"
FIGURES_DIR = RESULTS_DIR / "figures"
INTERMEDIATES_DIR = RESULTS_DIR / "intermediates"
TABLES_DIR = RESULTS_DIR / "tables"

# Stage 1 outputs: metadata CSVs
METADATA_JOINED_CSV = DATA_DIR / "patchseq_metadata_joined.csv"
EPHYS_JOINED_CSV = DATA_DIR / "patchseq_ephys_joined.csv"
COMBINED_CSV = DATA_DIR / "patchseq_combined.csv"

# Stage 2 outputs: h5ad
PATCHSEQ_H5AD = DATA_DIR / "patchseq_combined.h5ad"

# Stage 3 outputs: reference integration
REFERENCE_COMBINED_H5AD = INTERMEDIATES_DIR / "patchseq_reference_combined.h5ad"
KNN_LABELS_CSV = TABLES_DIR / "patchseq_knn_labels.csv"

# Stage 4 outputs: morphology
SWC_DIR = PROJECT_ROOT / "data" / "morphology" / "swc"
MORPHOLOGY_SVG_DIR = FIGURES_DIR / "morphology_svgs"
MORPHOLOGY_SVG_MAP_CSV = DATA_DIR / "specimen_to_morphology_svg_map.csv"

# Stage 5 outputs: traces
TRACE_SVG_MAP_CSV = DATA_DIR / "specimen_to_svg_map.csv"
TRACE_SYMLINK_DIR = FIGURES_DIR / "traces"
NWB_CACHE_DIR = PROJECT_ROOT / "data" / "nwb_cache"
TRACE_GENERATION_LOG_CSV = DATA_DIR / "trace_generation_log.csv"
TRACE_TARGET_AMPS = [-100, -20, 20, 100, 150, 250, 500, 1000]

# Stage 6 outputs: viewer
VIEWER_HTML = FIGURES_DIR / "patchseq_umap_interactive.html"

# Stage 7 outputs: accounting
COMPREHENSIVE_METADATA_CSV = DATA_DIR / "patchseq_comprehensive_metadata.csv"
DATA_ACCOUNTING_TXT = DATA_DIR / "data_source_accounting.txt"
MISSING_EPHYS_CSV = DATA_DIR / "missing_ephys_accounting.csv"

# ============================================================================
# Analysis parameters
# ============================================================================

# Expression data format
EXPRESSION_FORMAT = "log2(FPKM+1)"  # stored format in h5ad
NORMALIZE_TARGET_SUM = 1e4  # for scanpy-style normalization

# UMAP parameters
N_PCS = 30
N_NEIGHBORS = 15
MIN_DIST = 0.5
RANDOM_STATE = 42

# Ephys UMAP parameters
EPHYS_MIN_CELLS_PER_SUBCLASS = 5  # for feature selection

# Reference integration
N_HVGS = 3000
KNN_K = 15

# Morphology rendering
AVG_CORTEX_THICKNESS = 3006  # µm
AVG_LAYER_BOUNDARIES = {
    "L1_L2": 0.089,
    "L2_L3": 0.149,
    "L3_L4": 0.427,
}
PIA_OVERSHOOT_CAP = 0.5  # cap estimated pia if >50% of morph height above top
PIA_OVERSHOOT_TARGET = 0.3  # cap to 30% above

# Key ephys features for the combined table
KEY_EPHYS_FEATURES = [
    "sag", "tau", "input_resistance", "rheobase_i", "fi_fit_slope",
    "v_baseline", "avg_rate_hero",
    "upstroke_downstroke_ratio_short_square",
    "threshold_v_short_square", "width_short_square",
    "adapt_hero", "latency_rheo",
    "sag_tau", "sag_area",
    "peak_freq_chirp", "peak_ratio_chirp",
]

# Morphology compartment colors
MORPH_COLORS = {2: "steelblue", 3: "firebrick", 4: "salmon"}

# Figure style
FIGURE_DPI = 150
TITLE_FONTSIZE = 20
LABEL_FONTSIZE = 16
TICK_FONTSIZE = 13

# ============================================================================
# HTTP server configuration
# ============================================================================

SERVER_PORT = 8765
SERVER_ROOT = FIGURES_DIR  # python3 -m http.server 8765 --directory results/figures
